### PR TITLE
Feature vs2015

### PR DESCRIPTION
**Pull request by mattfelsen**
@prisonerjohn These changes look good! Can I pull them in? Any issues?

### CODE REVIEW

**Comment by prisonerjohn** [comment]
Hey, it all compiles and works in theory, but I couldn't get anything on screen (I believe it's because I have an Astra Pro, but wanted to confirm before submitting a PR).

**Comment by mattfelsen** [comment]
Ah right. I'll give it a shot, I've got an Astra Pro on lend here

**Comment by prisonerjohn** [comment]
brah come on

**Comment by mattfelsen** [comment]
what? I clearly didn't test it and then 5½ years went by

**Pull request closed without merging**
